NUMPY CODE:-

1. ...

In [1]:
import numpy as np

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # THIS IS 1D ARRAY
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
newarr1 = arr.reshape(2, 3, 2) # WITH RESHAPE FUNCTION NOW CONVERTED IT INTO 3D ARRAY
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [4]:
print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
newarr2 = arr.reshape(4,3) # WITH RESHAPE FUNCTION NOW CONVERTED INTO a 2D ARRAY - not required now.
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [7]:
newarr1 = [...,2]
print(newarr1)

[Ellipsis, 2]


In [8]:
newarr1 =[1,...]
print(newarr1)

[1, Ellipsis]


2. []

In [9]:
import numpy as np
b = np.arange(0,20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
b1 = np.reshape(b,(5,4))
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
b1[0,0]

0

In [12]:
b1[-1]

array([16, 17, 18, 19])

In [13]:
b1[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [14]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
b1>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [16]:
b1<=15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [17]:
a = np.array([ [ 0, 1, 2, 3, 4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34] ])
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [18]:
c = np.array( [True,False,True,False] ) # boolean row selector
print(a)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [19]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [20]:
d =  np.array([False,True,True,False,True])  # boolean column selector
a[:,d]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [21]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [22]:
i = np.array([0, 1, 2, 1]) # array of indices for the first axis
j = np.array([1,2,3,4]) # array of indices for the second axis

In [23]:
a[i,j]

array([ 1, 12, 23, 14])

3. abs() & 4. ABSOLUTE - both are same- Synonym for abs()

In [24]:
import numpy as np

ARR = np.arange(-4,5).reshape(3,3)
ARR

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [25]:
abs(ARR)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [26]:
ARR1 = 1.2 + 5j
ARR1

(1.2+5j)

In [27]:
abs(ARR1) #UNNDER-ROOT OF Square of of real part & imaginary part

5.141984052872976

In [28]:
np.absolute(ARR1) 

5.141984052872976

In [29]:
np.absolute([-10, -15])

array([10, 15])

5. accumulate 

 -computes the sum of the given initial value and the elements in the given range
 

In [30]:
import numpy as np

In [31]:
A1 = np.arange(0,10) 
print(A1) 

[0 1 2 3 4 5 6 7 8 9]


In [32]:
np.add.accumulate(A1) # Progressive SUM 

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [33]:
A2 = np.arange(1,6)
A2

array([1, 2, 3, 4, 5])

In [34]:
np.multiply.accumulate(A2)

array([  1,   2,   6,  24, 120])

In [35]:
AC = np.array([[1,2,3],[4,5,6]])
AC

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.add.accumulate(AC) # EVERY COLOMN GOT ACCUMULATE

array([[1, 2, 3],
       [5, 7, 9]])

In [37]:
np.multiply.accumulate(AC)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

6. add

In [38]:
import numpy as np

In [39]:
ar1 = [2, -6]
ar2 = [1, 3]
ar3 = [2.2, 8.7]
ar4 = [7, -3]
print(ar1, ar2, ar3,  ar4)

[2, -6] [1, 3] [2.2, 8.7] [7, -3]


In [40]:
np.add(ar1, ar2)

array([ 3, -3])

In [41]:
np.add(ar3, ar4)

array([9.2, 5.7])

In [42]:
C1 = 5+2j

In [43]:
np.add(ar3, C1)

array([ 7.2+2.j, 13.7+2.j])

7. all

Test whether all array elements along a given axis evaluate to True

In [44]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.all(a>5)

False

In [46]:
np.all(a>=0)

True

In [47]:
b7 = np.array([True, False, True, True])
np.all(b7)

False

8. allclose

-Returns True if two arrays are element-wise equal within a tolerance.

https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

In [48]:
np.allclose([0.1, 0.003], [0.11, 0.003])

False

In [49]:
np.allclose([0.11, 0.0033], [0.11000005, 0.00330001])

True

In [50]:
np.allclose([1e10,1e-8], [1.0001e10,1e-9])

False

In [51]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

9. alltrue- same as all function

In [52]:
b = np.array([True, False, True, True])
np.alltrue(b)

False

In [53]:
a = np.array([1, 5, 2, 7])
np.alltrue(a >= 5)

False

In [54]:
np.alltrue(a>0)

True

10.angle

Return the angle of the complex argument

In [55]:
np.angle([5+3j, 1j, 1.0])   # in RADIAN UNIT

array([0.5404195 , 1.57079633, 0.        ])

In [56]:
np.angle([5+3j, 1j, 1.0], deg=True)   # in Degree

array([30.96375653, 90.        ,  0.        ])

In [57]:
np.angle(1+1j,deg=True)

45.0

In [58]:
np.angle(1+1j,deg=False) # in RADIAN Unit

0.7853981633974483

11. any

-gives True if at least 1 element of a is True, otherwise False

In [59]:
c2 = np.array([True, False, True])
c2

array([ True, False,  True])

In [60]:
np.any(c2)

True

In [61]:
c3= np.arange(0,10)
c3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
any(c3>=5)

True

12. append

-Append values to the end of an array

In [63]:
c3= np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
c3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
c5 =np.append(c3, 10)
c5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.append(c5, ('ABC', 1 +2j))

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'ABC', '(1+2j)'],
      dtype='<U64')

In [66]:
c9= np.arange(10, 61, 10)
c9

array([10, 20, 30, 40, 50, 60])

In [67]:
np.append(c9, (70, 80, 90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
c10 =np.reshape(c9, (2,3))
c10

array([[10, 20, 30],
       [40, 50, 60]])

In [70]:
c11 = np.append(c10, [[70, 80, 90]], axis = 0)   # Add as a row
c11

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [71]:
c13 = np.append(c11, [[100], [120], [130]], axis = 1) # Add as a column
c13

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 120],
       [ 70,  80,  90, 130]])

13. apply_along_axis

Apply a function to 1-D slices along the given axis

It will apply function to axis

In [72]:
def func1(Q): #EX-1
    return (Q[0] + Q[-1])
abc = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.apply_along_axis(func1,0,abc) # When AXIS= 0 apply func1 to each COLOMN  of abc

array([ 8, 10, 12])

In [74]:
np.apply_along_axis(func1,1,abc) # When AXIS= 1 apply func1 to each ROW  of abc

array([ 4, 10, 16])

In [75]:
def func2(P): #2
    return (P[0] + P[-1])*2
abc1 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
abc1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.apply_along_axis(func2,0,abc)

array([16, 20, 24])

In [78]:
np.apply_along_axis(func2,1,abc)

array([ 8, 20, 32])

14. apply_over_axes()

-The numpy.apply_over_axes()applies a function repeatedly over multiple axes in an array.

In [79]:
D = np.arange(24)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [80]:
D=np.reshape(D, (2,3,4))
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [81]:
DQ = np.apply_over_axes(np.sum, D, [0,2]) # sum over all axes except axis=1, result has same shape as original 
DQ

array([[[ 60],
        [ 92],
        [124]]])

15. arrange

-Return evenly spaced values within a given interval.

In [82]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
np.arange(11.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [84]:
np.arange(8, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [85]:
np.arange(5,10) # start,stop

array([5, 6, 7, 8, 9])

In [86]:
np.arange(3,30,9) # start,stop,step

array([ 3, 12, 21])

16. arccos

--Trigonometric inverse cosine

-The inverse of cos so that, if y = cos(x), then x = arccos(y).

In [87]:
np.arccos([1, -1])   # We expect the arccos of 1 to be 0, and of -1 to be pi:

array([0.        , 3.14159265])

17. arccosh

Inverse hyperbolic cosine

In [88]:
np.arccosh([np.e, 10.0])

array([1.65745445, 2.99322285])

In [89]:
np.arccosh(1)

0.0

18. arcsin

--Trigonometric inverse Sine

In [90]:
np.arcsin([1, -1, 0])

array([ 1.57079633, -1.57079633,  0.        ])

19. arcsinh

Inverse hyperbolic Sine

In [91]:
np.arcsinh([np.e, 10.0])

array([1.72538256, 2.99822295])

20. arctan

-- Trigonometric inverse tangent, element-wise.

The inverse of tan, so that if y = tan(x) then x = arctan(y).

In [92]:
np.arctan([0, 1, -1])

array([ 0.        ,  0.78539816, -0.78539816])

21. arctan2

It computes element-wise arc tangent of arr1/arr2 choosing the quadrant correctly.

The quadrant is chosen so that arctan2(x1, x2)

In [93]:
# Consider four points in different quadrants

x = np.array([-1, +1, +1, -1])
y = np.array([-1, -1, +1, +1])

np.arctan2(y, x) * 180 / np.pi # In Degree Unit


array([-135.,  -45.,   45.,  135.])

In [94]:
np.arctan2(y, x) # In radian Unit

array([-2.35619449, -0.78539816,  0.78539816,  2.35619449])

In [95]:
np.arctan2([1., -1.], [0., 0.])

array([ 1.57079633, -1.57079633])

In [96]:
np.arctan2([0, 1], [1, 0])

array([0.        , 1.57079633])

22. arctanh

Inverse hyperbolic tangent

In [97]:
np.arctanh([0, -0.5])

array([ 0.        , -0.54930614])

23. argmax

--Returns the indices of the maximum values along an axis.

In [98]:
J =np.array([0, 11, 95, 2, -5, 55]) 

In [99]:
np.argmax(J)

2

In [100]:
j1 = np.arange(6).reshape(2,3) +10
j1

array([[10, 11, 12],
       [13, 14, 15]])

In [101]:
np.argmax(j1)

5

In [102]:
j2 = np.array([[10,50,30],[60,20,60]]) # If having more than 1 maximum values it will result in 1st index ---- NOTE

In [103]:
np.argmax(j2)

3

In [104]:
J2 = np.array([[1, 9, 0, 4], [2, 0, 8, -1]])
J2

array([[ 1,  9,  0,  4],
       [ 2,  0,  8, -1]])

In [105]:
np.argmax(J2, axis =0)           # for each column: the row index of the maximum value

array([1, 0, 1, 0], dtype=int64)

In [106]:
np.argmax(J2, axis=1)              # for each row: the column index of the maximum value

array([1, 2], dtype=int64)

24. argmin

--Returns the indices of the Minimum values along an axis.

In [107]:
d4 =np.array([0, 11, 95, 2, -5, 55]) 
d4

array([ 0, 11, 95,  2, -5, 55])

In [108]:
np.argmin(d4)

4

In [109]:
d9 = np.arange(6).reshape(2,3) +10
d9

array([[10, 11, 12],
       [13, 14, 15]])

In [110]:
np.argmin(d9)

0

In [111]:
da2=np.array([[50,50,10],[60,10,40]])
da2

array([[50, 50, 10],
       [60, 10, 40]])

In [112]:
np.argmin(da2) # If having more than 1 min. vales it will return 1st index ------ NOTE

2

In [113]:
np.argmin(da2, axis=0) # for each column: the row index of the maximum value

array([0, 1, 0], dtype=int64)

In [114]:
np.argmin(da2, axis=1)   # for each row: the column index of the maximum value

array([2, 1], dtype=int64)

25. argsoft

--- Returns the indices that would sort an array

In [115]:
AB1 = np.array([ 2, 0,  1, 5, 4, 1, 9])
AB1

array([2, 0, 1, 5, 4, 1, 9])

In [116]:
np.argsort(AB1) # It will sort & write Indices of elemets

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [117]:
# FOR SORTING OF VALUES

BQ = np.argsort(AB1)
BQ

array([1, 2, 5, 0, 4, 3, 6], dtype=int64)

In [118]:
AB1[BQ] # same effect as sort() but on Values

array([0, 1, 1, 2, 4, 5, 9])

In [119]:
aq1 = np.array([[8,4,1],[2,0,9]])
aq1

array([[8, 4, 1],
       [2, 0, 9]])

In [120]:
JQ1 = aq1.argsort(axis=0) # sorts on columns. NOT the same as aq1.sort(axis=1)
JQ1

array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

In [121]:
aq1[JQ1,[[0,1,2], [0,1,2]]] # 2-D arrays need fancy indexing if you want to sort them.

array([[2, 0, 1],
       [8, 4, 9]])

In [122]:
JQ1 = aq1.argsort(axis=1)  # sort along rows. Can use aq1.argsort(axis=-1) for last axis.
JQ1 

array([[2, 1, 0],
       [1, 0, 2]], dtype=int64)

26. array

To Create an array.

In [123]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [124]:
np.array([[1, 2], [3, 4]]) # More than one dimension:

array([[1, 2],
       [3, 4]])

In [125]:
np.array([1, 2, 3], dtype=complex) # Type provided:

array([1.+0.j, 2.+0.j, 3.+0.j])

In [126]:
np.array([1, 2, 3], ndmin=2)  # Minimum dimensions 2:

array([[1, 2, 3]])

In [127]:
np.array(1, copy=0, subok=1, ndmin=1) # basically equivalent to atleast_1d

array([1])

In [128]:
np.array(1, copy=0, subok=1, ndmin=2) # basically equivalent to atleast_2d

array([[1]])

In [129]:
np.array(1, subok=1, ndmin=2) # like atleast_2d but always makes a copy

array([[1]])

27. arrayrange

-Synonym for arange.

28. array split

-Split an array into multiple sub-arrays

In [131]:
c4 = np.array([[1,2,3,4],[5,6,7,8]])
c4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [132]:
np.array_split(c4,2,axis=0) # split c4 in 2 parts. row-wise

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [133]:
np.array_split(c4,4,axis=1) # split c4 in 4 parts, column-wise

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [134]:
np.array_split(c4,3,axis=1) # impossible to split in 3 equal parts -> first part(s) are big

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [135]:
np.array_split(c4,3,axis=0) # split c4 in 3 parts. row-wise

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([], shape=(0, 4), dtype=int32)]

In [136]:
np.array_split(c4,[2,3],axis=1) # make c4 split before the 2nd and the 3rd column

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

29. asarray

Convert the input to an array.

In [137]:
my_list = [1, 3, 5, 7, 9]
np.asarray(my_list)     # List to array 

array([1, 3, 5, 7, 9])

In [138]:
my_tuple = ([1, 3, 9], [8, 2, 6])
np.asarray(my_tuple)   # Tuple to array 

array([[1, 3, 9],
       [8, 2, 6]])

In [139]:
m = np.matrix('1 2; 5 8')
m

matrix([[1, 2],
        [5, 8]])

In [140]:
B9 = np.asarray(m) # B9 is a array type with same contents as m -- data is not copied
B9

array([[1, 2],
       [5, 8]])

In [141]:
m[0,1] = -190
m

matrix([[   1, -190],
        [   5,    8]])

In [142]:
B9 # though a copy of m was not made, modifying m modified B9 as well 

array([[   1, -190],
       [   5,    8]])

30. asanyarray

-Convert the input to an ndarray, but pass ndarray subclasses through.

In [143]:
c7 = np.array([[1,2],[5,8]])
c7

array([[1, 2],
       [5, 8]])

In [144]:
mq = np.matrix('1 2; 5 8')
mq

matrix([[1, 2],
        [5, 8]])

In [145]:
np.asanyarray(c7) # the array c7 is returned unmodified

array([[1, 2],
       [5, 8]])

In [146]:
np.asanyarray(mq) # the matrix mq is returned unmodified

matrix([[1, 2],
        [5, 8]])

In [147]:
my_tuple1 = ([1, 3, 9], [8, 2, 6])
my_tuple1

([1, 3, 9], [8, 2, 6])

In [148]:
np.asanyarray(my_tuple1)

array([[1, 3, 9],
       [8, 2, 6]])

31. asmatrix

Interpret the input as a matrix.

In [149]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)  # m is matrix type with same contents as x -- data is not copied
m

matrix([[1, 2],
        [3, 4]])

In [150]:
x[0,0] = 5
print(m)

[[5 2]
 [3 4]]


In [151]:
print(x) # no copy was made so modifying x modifies m, and vice versa

[[5 2]
 [3 4]]


32. astype

Copy of the array, cast to a specified type.

In [152]:
x6 = np.array([1, 2, 2.5])
x6

array([1. , 2. , 2.5])

In [153]:
x6.astype(int) # x6 default type was float with this command converting into int type

array([1, 2, 2])

In [154]:
x6.astype(None) # None implies converting to the default type

array([1. , 2. , 2.5])

33. atleast 1d

Convert inputs to arrays with at least one dimension

In [155]:
a01 = 1 # 0-d array
b01 = np.array([2,3]) # 1-d array
c01 = np.array([[4,5],[6,7]]) # 2-d array
d01 = np.arange(8).reshape(2,2,2) # 3-d array
d01

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
a01

1

In [157]:
b01

array([2, 3])

In [158]:
c01

array([[4, 5],
       [6, 7]])

In [159]:
np.atleast_1d(a01,b01,c01,d01) # all output arrays have dim >= 1

[array([1]),
 array([2, 3]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

34. atleast_2d()

-View inputs as arrays with at least two dimensions.

In [160]:
a11 = 1 # 0-d array
b11 = np.array([2,3]) # 1-d array
c11 = np.array([[4,5],[6,7]]) # 2-d array
d11 = np.arange(8).reshape(2,2,2) # 3-d array

In [161]:
a11

1

In [162]:
b11

array([2, 3])

In [163]:
c11

array([[4, 5],
       [6, 7]])

In [164]:
d11

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [165]:
np.atleast_2d(a11,b11,c11,d11) # all output arrays have dim >= 2

[array([[1]]),
 array([[2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

35. atleast_3d()

-View inputs as arrays with at least three dimensions.

In [166]:
f = 1 # 0-d array
g = np.array([2,3]) # 1-d array
h = np.array([[4,5],[6,7]]) # 2-d array
i = np.arange(8).reshape(2,2,2) # 3-d array

In [167]:
f

1

In [168]:
g

array([2, 3])

In [169]:
h

array([[4, 5],
       [6, 7]])

In [170]:
i

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [171]:
np.atleast_3d(f,g,h,i) # all output arrays have dim >= 3

[array([[[1]]]),
 array([[[2],
         [3]]]),
 array([[[4],
         [5]],
 
        [[6],
         [7]]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]

36. Average

Compute the weighted average along the specified axis.

In [172]:
bz = np.array([1,4,5,7,5])
bz

array([1, 4, 5, 7, 5])

In [173]:
np.average(bz) # average always comes in float

4.4

In [174]:
w = np.array([0.1, 0.2, 0.5, 0.2, 0.2]) # weights, not necessarily normalized

In [175]:
np.average(bz,weights=w) # This will give weighted avg. = sum(Element * weights) / sum(weights)

4.833333333333333